chorelist/chorelist/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^chores/',include('chores.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

chorelist/chores/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^newlist/$', views.newlist, name='newlist'),
    url(r'^(?P<chorelist_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<chorelist_id>[0-9]+)/chores/(?P<chore_id>[0-9]+)/$', views.choredetail, name='choredetail'),
    url(r'^(?P<chorelist_id>[0-9]+)/chores/(?P<chore_id>[0-9]+)/update/$', views.updatechore, name='updatechore')
]

chorelist/chores/models.py
from django.db import models

# Create your models here.

class ChoreList(models.Model):
    name = models.CharField(max_length=100)
    due_date = models.DateTimeField()

    def __str__(self):
        return self.name


class Chore(models.Model):
    chore_list = models.ForeignKey(ChoreList)
    name = models.CharField(max_length=100)
    due_date = models.DateTimeField()
    complete = models.BooleanField(default=True)

    def __str__(self):
        return self.name

chorelist/chores/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import ChoreList, Chore
from django.core.urlresolvers import reverse

def index(request):
    lists = ChoreList.objects.all()
    return render(request, 'chores/index.html', {'chorelists': lists})

def newlist(request):
    if request.POST:
        list = ChoreList(name=request.POST['name'], due_date=request.POST['duedate'])
        list.save()
        return HttpResponseRedirect('/chores')
    else:
        return render(request, 'chores/newlist.html', {})

def detail(request, chorelist_id):
    list = get_object_or_404(ChoreList, pk=chorelist_id)
    return render(request, 'chores/detail.html', {'chorelist': list})

def choredetail(request, chorelist_id, chore_id):
    list = get_object_or_404(ChoreList, pk=chorelist_id)
    chore = get_object_or_404(Chore, pk=chore_id)
    return render(request, 'chores/choredetail.html', {'chorelist': list, 'chore': chore})

def updatechore(request, chorelist_id, chore_id):
    chore = get_object_or_404(Chore, pk=chore_id)
    if 'complete' in request.POST:
        chore.complete = True
    else:
        chore.complete = False
    chore.save()
    return HttpResponseRedirect('/chores/' + chorelist_id + '/chores/' + chore_id)

chorelist/chores/templates/chores/choredetail.html
<h1> {{chore}} </h1>

<p> Due Date: {{chore.due_date}} </p>

<form action="/chores/{{chorelist.id}}/chores/{{chore.id}}/update/" method="post">
	{%csrf_token %}
	
	<label form="complete"> Is Complete</label>
	{% if chore.complete %}
		<input type ="checkbox" name="complete" id="complete" checked />
	{% else %}
		<input type ="checkbox" name="complete" id="complete" />
	{% endif %}
	
	<br/>
	<input type="submit" value="Update"/>
	 
	
</form>

chorelist/chores/templates/chores/detail.html
<h1> {{ chorelist }} </h1>

<ul>
    {%  for chore in chorelist.chore_set.all %}
        <li> <a href="/chores/{{chorelist.id}}/chores/{{chore.id}}">{{chore}}</a></li>
    {%  endfor  %}

</ul>

chorelist/chores/templates/chores/index.html
{% if chorelists %}
	<ul>
		{% for chorelist in chorelists %}
			<li><a href="/chores/{{chorelist.id}}/">{{chorelist.name}}</a></li>

		{% endfor %}

	</ul>


{% else %}
	<p> No Chore list are currently available</p>

{%endif %}
<a href="/chores/newlist">Create a new Chore List</a>

chorelist/chores/templates/chores/newlist.html
<h1>New List</h1>

<form action="/chores/newlist/" method="post">
    {%  csrf_token %}
    <label for="name">List Name</label>
    <input type="textbox" name="name" placeholder="Enter a name" />
    <br/><br/>
    <label for="duedate">Due Date</label>
    <input type="datetime-local" name="duedate" id="duedate" />
    <br/><br/>
    <input type="submit" value="Create"/>





</form>